TRUNCATE TABLE publisher RESTART IDENTITY CASCADE;
VACUUM FULL publisher;

TRUNCATE TABLE book_author;
VACUUM FULL book_author;

TRUNCATE TABLE author RESTART IDENTITY CASCADE;
VACUUM FULL author;

TRUNCATE TABLE book RESTART IDENTITY CASCADE;
VACUUM FULL book;
