### Get all Customers

GET http://localhost:8080/sfg7/api/v1/customer
Content-Type: application/json
Accept: application/json

> {%
	client.test(">>> Response status is 200", function () {
		client.assert(response.status === 200, "Response status is not 200");
	});
%}


###


GET http://localhost:8080/sfg7/api/v1/customer/0c5f8291-b3d5-4e59-8010-c4d7908f393c
Content-Type: application/json
Accept: application/json

> {%
	client.test(">>> Response status is 200", function () {
		client.assert(response.status === 200, "Response status is not 200");
	});

	client.test(">>> Response contains only one Customer object", function () {
		client.assert(!Array.isArray(response.body), ">>> Response body should not be an array");
		client.assert(typeof response.body === 'object', "Response body should be an object");
	});
%}


### Save a new Customer

POST http://localhost:8080/sfg7/api/v1/customer
Content-Type: application/json
Accept: application/json

{
  "version": 1,
  "name": "Rogers"
}


### Update Customer by ID


PUT http://localhost:8080/sfg7/api/v1/customer/7e79fe98-6b84-4760-9c41-5cf2295dbaf9
Content-Type: application/json
Accept: application/json

{
  "name": "Rogers-1"
}


### Delete Customer by Customer ID

DELETE http://localhost:8080/sfg7/api/v1/customer/fc4fbfc7-4b42-4883-88cd-1b4d6e302404
Content-Type: application/json
Accept: application/json


### Patch Customer by Customer ID

PATCH http://localhost:8080/sfg7/api/v1/customer/109b47cf-8986-4efb-a623-844237bbd936
Content-Type: application/json
Accept: application/json

{
  "name": "Telus"
}