TRUNCATE TABLE beer RESTART IDENTITY CASCADE;
VACUUM FULL beer;

TRUNCATE TABLE customer RESTART IDENTITY CASCADE;
VACUUM FULL customer;

TRUNCATE TABLE flashcard RESTART IDENTITY CASCADE;
VACUUM FULL flashcard;
