TRUNCATE TABLE student RESTART IDENTITY CASCADE;;
VACUUM FULL student;

TRUNCATE TABLE course RESTART IDENTITY CASCADE;
VACUUM FULL course;

TRUNCATE TABLE enrollment RESTART IDENTITY CASCADE;
VACUUM FULL enrollment;